# -*- coding: utf-8 -*-
"""Gaussin Distribution with real data-Questions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10bR_aGw0T3d8HeUFt4Db9O-nj2YtaHGG
"""

import pandas as pd
import scipy.stats as ss
import matplotlib.pyplot as plt
import numpy as np

"""Load the file weights.csv with babies weights into a pandas dataframe."""

#load the data
dataset = ...

dataset.head()

weights = dataset.baby_weight

"""Plot the histogram for the weights."""

count, bins, ignored = plt.hist(weights, bins = 50, density=True, stacked=True)

"""Use normaltest() from scipy.stats to test whether the sample of weights differs from a normal distribution."""

_ , p = ss.normaltest(weights)
if p < 0.05:  # null hypothesis: x comes from a normal distribution
    print("The null hypothesis can be rejected")
else:
    print("The null hypothesis cannot be rejected")

"""Compute the mean and standard deviation of the sample of exam durtions"""

mu = ...
sigma = ...

"""Plot the histogram of weights and the probability distribution curve."""

count, bins, ignored = plt.hist(weights, bins = 50, density=True, stacked=True)
plt.plot(bins, 1/(sigma * np.sqrt(2 * np.pi)) *
    np.exp( - (bins - mu)**2 / (2 * sigma**2) ),       linewidth=3, color='y')
plt.show()

"""Declare a normally distributed model for babies weights"""

predictive_model = ...

"""### Answer the following question.

1. What is the probability that a random selected baby  with weigh 10.3 lbs?
"""



"""2. What is the probability that a randomly selected weight will exceeds 12 lbs?"""



"""3. What is the probability that a randomly selected weight will be between 7 and 11 lbs?"""

